# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34f0344a286f7c1ca43dd9b9a85ba65b"
name = "poc-meta"
handle = "poc-meta"
application_url = "https://theme-nigeria-mercy-founded.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "syf-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://theme-nigeria-mercy-founded.trycloudflare.com/auth/callback",
  "https://theme-nigeria-mercy-founded.trycloudflare.com/auth/shopify/callback",
  "https://theme-nigeria-mercy-founded.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
