# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc7a3dbd13ce913d0f9e0fd3d2525202"
name = "poc-meta-app"
handle = "poc-meta-app"
application_url = "https://nevada-galleries-design-suddenly.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "poc-meta.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://nevada-galleries-design-suddenly.trycloudflare.com/auth/callback",
  "https://nevada-galleries-design-suddenly.trycloudflare.com/auth/shopify/callback",
  "https://nevada-galleries-design-suddenly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
